[book]
title = "Idiomatic Rust in Simple Steps"
description = "Learn idiomatic Rust in simple steps even if you have no former knowledge"
authors = ["Daniel Mason"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "docs"
create-missing = true

[preprocessor.external-links]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
