name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure cargo binstall is installed
        uses: cargo-bins/cargo-binstall@main

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
#          mdbook-version: '0.4.43'
          mdbook-version: 'latest'

      - name: Add mdBook extensions
        run: |
          cargo binstall mdbook-mermaid
#          cargo binstall mdbook-external-links

      - name: Test
        run: mdbook test

      - name: Build
        run: mdbook build
