name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure cargo binstall is installed
        uses: cargo-bins/cargo-binstall@main

      - name: Add mdBook and extensions
        run: |
          cargo binstall mdbook
          cargo binstall mdbook-external-links
          cargo binstall mdbook-mermaid

      - name: Test
        run: mdbook test

      - name: Build
        run: mdbook build
